language: go
sudo: false
go:
  - tip
before_install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo
script:
  - glide install
  - go vet
  - go env
  - ginkgo -cover
  - goveralls -service=travis-ci
