language: go
sudo: false
go:
  - tip
matrix:
  include:
    - os: osx
    - os: linux

before_install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/onsi/ginkgo/ginkgo
jobs:
  include:
    - stage: setup
      script:
        - glide install
        - export PATH=$GOPATH/bin:$PATH
        - go env
    - stage: test
      script:
        - go vet
        - go test -cover
        - goveralls -service=travis-ci
    - stage: build
      script:
        - go build
