language: go
sudo: false
matrix:
  include:
    - os: osx
      go: tip
    - os: linux
      go: tip

before_install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/onsi/ginkgo/ginkgo
install:
  - glide install
  - export PATH=$GOPATH/bin:$PATH
  - go env
test:
  - go vet
  - go test -cover
  - goveralls -service=travis-ci
build:
  - go build
