# appveyor.yml
build: off

environment:
  GOPATH: C:\gopath
  APPVEYOR_BUILD_FOLDER: C:\gopath\src\github.com\kevinjpickard\demdj
  GO111MODULE: on

stack: go 1.11.0

before_build:
  - ps: go mod vendor

test_script:
  - ps: go test -v -mod=vendor -cover

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8ADMF8Dx7v7ixcph9LqwttcbUOGuwb5SSSGKyoBl5Utny1nLSXeeI/YVIWnUOh0c43Dok7yepW5EZnP8IQX41uUSZOBhvEdfqtCyiU4fIls=
