# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\kevinjpickard\demdj

environment:
  GOPATH: c:\gopath

stack: go 1.10

init:
  - ps: Get-Location

before_test:
  - go vet ./...

test_script:
  - go test ./...
