# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\kevinjpickard\demdj

environment:
  GOPATH: C:\gopath
  APPVEYOR_BUILD_FOLDER: C:\gopath\src\github.com\kevinjpickard\demdj

stack: go 1.10

install:
  - ps: go get -u github.com/Masterminds/glide
  - ps: go get github.com/mattn/goveralls
  - ps: go get golang.org/x/tools/cmd/cover
  - ps: go get -u github.com/onsi/ginkgo/ginkgo

before_build:
  - ps: $env:PATH="$env:PATH;$env:GOPATH\bin"
  - ps: glide -q install
  - ps: go vet

build_script:
  - ps: go build

test_script:
  - ps: go test -cover 

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 8ADMF8Dx7v7ixcph9LqwttcbUOGuwb5SSSGKyoBl5Utny1nLSXeeI/YVIWnUOh0c43Dok7yepW5EZnP8IQX41uUSZOBhvEdfqtCyiU4fIls=
